import { Player, PlayerRole } from './types';

export const SAMPLE_PLAYERS: Player[] = [
  { id: '1', name: 'Virat Kohli', role: PlayerRole.BATTER, rating: 9.5, points: 10, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '2', name: 'Rohit Sharma', role: PlayerRole.BATTER, rating: 9.2, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '3', name: 'Babar Azam', role: PlayerRole.BATTER, rating: 9.0, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '4', name: 'Ben Stokes', role: PlayerRole.ALL_ROUNDER, rating: 9.3, points: 9, battingPosition: 'Middle Order', bowlingType: 'Fast', isDeathBowler: true },
  { id: '5', name: 'Hardik Pandya', role: PlayerRole.ALL_ROUNDER, rating: 8.8, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast', isDeathBowler: true },
  { id: '6', name: 'MS Dhoni', role: PlayerRole.WICKETKEEPER, rating: 9.4, points: 9, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '7', name: 'Ravindra Jadeja', role: PlayerRole.ALL_ROUNDER, rating: 9.1, points: 9, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '8', name: 'Jasprit Bumrah', role: PlayerRole.BOWLER, rating: 9.6, points: 10, bowlingType: 'Fast', isDeathBowler: true },
  { id: '9', name: 'Rashid Khan', role: PlayerRole.BOWLER, rating: 9.3, points: 9, bowlingType: 'Spin' },
  { id: '10', name: 'Mitchell Starc', role: PlayerRole.BOWLER, rating: 9.1, points: 9, bowlingType: 'Fast', isDeathBowler: true },
  { id: '11', name: 'Steve Smith', role: PlayerRole.BATTER, rating: 8.9, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '12', name: 'Kane Williamson', role: PlayerRole.BATTER, rating: 9.0, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '13', name: 'Jos Buttler', role: PlayerRole.WICKETKEEPER, rating: 9.2, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '14', name: 'Pat Cummins', role: PlayerRole.BOWLER, rating: 9.2, points: 9, bowlingType: 'Fast', isDeathBowler: true },
  { id: '15', name: 'Trent Boult', role: PlayerRole.BOWLER, rating: 8.9, points: 8, bowlingType: 'Fast' },
  { id: '16', name: 'Glenn Maxwell', role: PlayerRole.ALL_ROUNDER, rating: 8.7, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '17', name: 'KL Rahul', role: PlayerRole.WICKETKEEPER, rating: 8.6, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '18', name: 'Shaheen Afridi', role: PlayerRole.BOWLER, rating: 9.0, points: 9, bowlingType: 'Fast' },
  { id: '19', name: 'Quinton de Kock', role: PlayerRole.WICKETKEEPER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '20', name: 'David Warner', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '21', name: 'Sachin Tendulkar', role: PlayerRole.BATTER, rating: 9.9, points: 10, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '22', name: 'Kumar Sangakkara', role: PlayerRole.WICKETKEEPER, rating: 9.5, points: 10, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '23', name: 'Shane Warne', role: PlayerRole.BOWLER, rating: 9.8, points: 10, bowlingType: 'Spin' },
  { id: '24', name: 'Jacques Kallis', role: PlayerRole.ALL_ROUNDER, rating: 9.9, points: 10, battingPosition: 'Top Order', bowlingType: 'Fast' },
  { id: '25', name: 'Adam Gilchrist', role: PlayerRole.WICKETKEEPER, rating: 9.6, points: 10, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '26', name: 'Wasim Akram', role: PlayerRole.BOWLER, rating: 9.7, points: 10, bowlingType: 'Fast', isDeathBowler: true },
  { id: '27', name: 'Muttiah Muralitharan', role: PlayerRole.BOWLER, rating: 9.8, points: 10, bowlingType: 'Spin' },
  { id: '28', name: 'Ricky Ponting', role: PlayerRole.BATTER, rating: 9.6, points: 10, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '29', name: 'Viv Richards', role: PlayerRole.BATTER, rating: 9.8, points: 10, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '30', name: 'Imran Khan', role: PlayerRole.ALL_ROUNDER, rating: 9.7, points: 10, battingPosition: 'Middle Order', bowlingType: 'Fast', isDeathBowler: true },
  { id: '31', name: 'Brian Lara', role: PlayerRole.BATTER, rating: 9.8, points: 10, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '32', name: 'Glenn McGrath', role: PlayerRole.BOWLER, rating: 9.7, points: 10, bowlingType: 'Fast' },
  { id: '33', name: 'Dale Steyn', role: PlayerRole.BOWLER, rating: 9.6, points: 10, bowlingType: 'Fast', isDeathBowler: true },
  { id: '34', name: 'AB de Villiers', role: PlayerRole.WICKETKEEPER, rating: 9.8, points: 10, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '35', name: 'Chris Gayle', role: PlayerRole.BATTER, rating: 9.4, points: 9, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '36', name: 'Mahela Jayawardene', role: PlayerRole.BATTER, rating: 9.3, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '37', name: 'Shubman Gill', role: PlayerRole.BATTER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '38', name: 'Yashasvi Jaiswal', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '39', name: 'Rishabh Pant', role: PlayerRole.WICKETKEEPER, rating: 8.9, points: 8, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '40', name: 'Mohammed Shami', role: PlayerRole.BOWLER, rating: 9.1, points: 9, bowlingType: 'Fast', isDeathBowler: true },
  { id: '41', name: 'Mohammed Siraj', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Fast' },
  { id: '42', name: 'Kuldeep Yadav', role: PlayerRole.BOWLER, rating: 8.9, points: 8, bowlingType: 'Spin' },
  { id: '43', name: 'Travis Head', role: PlayerRole.BATTER, rating: 9.1, points: 9, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '44', name: 'Mitchell Marsh', role: PlayerRole.ALL_ROUNDER, rating: 8.6, points: 8, battingPosition: 'Top Order', bowlingType: 'Fast' },
  { id: '45', name: 'Adam Zampa', role: PlayerRole.BOWLER, rating: 8.8, points: 8, bowlingType: 'Spin' },
  { id: '46', name: 'Harry Brook', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '47', name: 'Liam Livingstone', role: PlayerRole.ALL_ROUNDER, rating: 8.5, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '48', name: 'Jofra Archer', role: PlayerRole.BOWLER, rating: 9.0, points: 9, bowlingType: 'Fast', isDeathBowler: true },
  { id: '49', name: 'Adil Rashid', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Spin' },
  { id: '50', name: 'Daryl Mitchell', role: PlayerRole.ALL_ROUNDER, rating: 8.7, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '51', name: 'Rachin Ravindra', role: PlayerRole.ALL_ROUNDER, rating: 8.6, points: 8, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '52', name: 'Devon Conway', role: PlayerRole.WICKETKEEPER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '53', name: 'Heinrich Klaasen', role: PlayerRole.WICKETKEEPER, rating: 9.2, points: 9, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '54', name: 'David Miller', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '55', name: 'Kagiso Rabada', role: PlayerRole.BOWLER, rating: 9.2, points: 9, bowlingType: 'Fast', isDeathBowler: true },
  { id: '56', name: 'Anrich Nortje', role: PlayerRole.BOWLER, rating: 8.8, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '57', name: 'Mohammad Rizwan', role: PlayerRole.WICKETKEEPER, rating: 8.9, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '58', name: 'Naseem Shah', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Fast' },
  { id: '59', name: 'Haris Rauf', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '60', name: 'Wanindu Hasaranga', role: PlayerRole.ALL_ROUNDER, rating: 8.9, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '61', name: 'Matheesha Pathirana', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '62', name: 'Andre Russell', role: PlayerRole.ALL_ROUNDER, rating: 9.0, points: 9, battingPosition: 'Finisher', bowlingType: 'Fast', isDeathBowler: true },
  { id: '63', name: 'Sunil Narine', role: PlayerRole.ALL_ROUNDER, rating: 9.1, points: 9, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '64', name: 'Nicholas Pooran', role: PlayerRole.WICKETKEEPER, rating: 8.9, points: 8, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '65', name: 'Mohammad Nabi', role: PlayerRole.ALL_ROUNDER, rating: 8.5, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '66', name: 'Mujeeb Ur Rahman', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Spin' },
  { id: '67', name: 'Suryakumar Yadav', role: PlayerRole.BATTER, rating: 9.3, points: 9, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '68', name: 'Rinku Singh', role: PlayerRole.BATTER, rating: 8.5, points: 8, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '69', name: 'Axar Patel', role: PlayerRole.ALL_ROUNDER, rating: 8.7, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '70', name: 'Josh Hazlewood', role: PlayerRole.BOWLER, rating: 9.0, points: 9, bowlingType: 'Fast' },
  { id: '71', name: 'Ruturaj Gaikwad', role: PlayerRole.BATTER, rating: 8.9, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '72', name: 'Shivam Dube', role: PlayerRole.ALL_ROUNDER, rating: 8.7, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '73', name: 'Matheesha Pathirana', role: PlayerRole.BOWLER, rating: 8.8, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '74', name: 'Tushar Deshpande', role: PlayerRole.BOWLER, rating: 8.2, points: 7, bowlingType: 'Fast' },
  { id: '75', name: 'Daryl Mitchell', role: PlayerRole.ALL_ROUNDER, rating: 8.7, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '76', name: 'Ravindra Jadeja', role: PlayerRole.ALL_ROUNDER, rating: 9.1, points: 9, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '77', name: 'Ajinkya Rahane', role: PlayerRole.BATTER, rating: 8.3, points: 7, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '78', name: 'Deepak Chahar', role: PlayerRole.BOWLER, rating: 8.5, points: 8, bowlingType: 'Fast' },
  { id: '79', name: 'Maheesh Theekshana', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Spin' },
  { id: '80', name: 'Ishan Kishan', role: PlayerRole.WICKETKEEPER, rating: 8.6, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '81', name: 'Tilak Varma', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '82', name: 'Tim David', role: PlayerRole.BATTER, rating: 8.4, points: 7, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '83', name: 'Gerald Coetzee', role: PlayerRole.BOWLER, rating: 8.5, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '84', name: 'Piyush Chawla', role: PlayerRole.BOWLER, rating: 8.2, points: 7, bowlingType: 'Spin' },
  { id: '85', name: 'Akash Madhwal', role: PlayerRole.BOWLER, rating: 8.1, points: 7, bowlingType: 'Fast', isDeathBowler: true },
  { id: '86', name: 'Naman Dhir', role: PlayerRole.ALL_ROUNDER, rating: 7.8, points: 6, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '87', name: 'Faf du Plessis', role: PlayerRole.BATTER, rating: 8.9, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '88', name: 'Rajat Patidar', role: PlayerRole.BATTER, rating: 8.5, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '89', name: 'Cameron Green', role: PlayerRole.ALL_ROUNDER, rating: 8.8, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '90', name: 'Dinesh Karthik', role: PlayerRole.WICKETKEEPER, rating: 8.4, points: 7, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '91', name: 'Yash Dayal', role: PlayerRole.BOWLER, rating: 8.0, points: 7, bowlingType: 'Fast' },
  { id: '92', name: 'Lockie Ferguson', role: PlayerRole.BOWLER, rating: 8.5, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '93', name: 'Will Jacks', role: PlayerRole.ALL_ROUNDER, rating: 8.6, points: 8, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '94', name: 'Shreyas Iyer', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '95', name: 'Venkatesh Iyer', role: PlayerRole.ALL_ROUNDER, rating: 8.4, points: 7, battingPosition: 'Top Order', bowlingType: 'Fast' },
  { id: '96', name: 'Varun Chakaravarthy', role: PlayerRole.BOWLER, rating: 8.8, points: 8, bowlingType: 'Spin' },
  { id: '97', name: 'Harshit Rana', role: PlayerRole.BOWLER, rating: 8.3, points: 7, bowlingType: 'Fast', isDeathBowler: true },
  { id: '98', name: 'Vaibhav Arora', role: PlayerRole.BOWLER, rating: 8.1, points: 7, bowlingType: 'Fast' },
  { id: '99', name: 'Phil Salt', role: PlayerRole.WICKETKEEPER, rating: 8.7, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '100', name: 'Abhishek Sharma', role: PlayerRole.ALL_ROUNDER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '101', name: 'Bhuvneshwar Kumar', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '102', name: 'T Natarajan', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '103', name: 'Mayank Markande', role: PlayerRole.BOWLER, rating: 8.1, points: 7, bowlingType: 'Spin' },
  { id: '104', name: 'Nitish Kumar Reddy', role: PlayerRole.ALL_ROUNDER, rating: 8.2, points: 7, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '105', name: 'Sanju Samson', role: PlayerRole.WICKETKEEPER, rating: 9.0, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '106', name: 'Yuzvendra Chahal', role: PlayerRole.BOWLER, rating: 9.1, points: 9, bowlingType: 'Spin' },
  { id: '107', name: 'Ravichandran Ashwin', role: PlayerRole.ALL_ROUNDER, rating: 8.9, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '108', name: 'Riyan Parag', role: PlayerRole.BATTER, rating: 8.5, points: 8, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '109', name: 'Shimron Hetmyer', role: PlayerRole.BATTER, rating: 8.4, points: 7, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '110', name: 'Dhruv Jurel', role: PlayerRole.WICKETKEEPER, rating: 8.2, points: 7, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '111', name: 'Avesh Khan', role: PlayerRole.BOWLER, rating: 8.4, points: 7, bowlingType: 'Fast', isDeathBowler: true },
  { id: '112', name: 'Sandeep Sharma', role: PlayerRole.BOWLER, rating: 8.5, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '113', name: 'Sai Sudharsan', role: PlayerRole.BATTER, rating: 8.6, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '114', name: 'Rahul Tewatia', role: PlayerRole.ALL_ROUNDER, rating: 8.3, points: 7, battingPosition: 'Finisher', bowlingType: 'Spin' },
  { id: '115', name: 'Mohit Sharma', role: PlayerRole.BOWLER, rating: 8.4, points: 7, bowlingType: 'Fast', isDeathBowler: true },
  { id: '116', name: 'Noor Ahmad', role: PlayerRole.BOWLER, rating: 8.5, points: 8, bowlingType: 'Spin' },
  { id: '117', name: 'Azmatullah Omarzai', role: PlayerRole.ALL_ROUNDER, rating: 8.2, points: 7, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '118', name: 'Marcus Stoinis', role: PlayerRole.ALL_ROUNDER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'Fast' },
  { id: '119', name: 'Ravi Bishnoi', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Spin' },
  { id: '120', name: 'Krunal Pandya', role: PlayerRole.ALL_ROUNDER, rating: 8.5, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '121', name: 'Ayush Badoni', role: PlayerRole.BATTER, rating: 8.0, points: 7, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '122', name: 'Mayank Yadav', role: PlayerRole.BOWLER, rating: 8.4, points: 7, bowlingType: 'Fast' },
  { id: '123', name: 'Naveen-ul-Haq', role: PlayerRole.BOWLER, rating: 8.5, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '124', name: 'Prithvi Shaw', role: PlayerRole.BATTER, rating: 8.2, points: 7, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '125', name: 'Khaleel Ahmed', role: PlayerRole.BOWLER, rating: 8.4, points: 7, bowlingType: 'Fast' },
  { id: '126', name: 'Ishant Sharma', role: PlayerRole.BOWLER, rating: 8.2, points: 7, bowlingType: 'Fast' },
  { id: '127', name: 'Jake Fraser-McGurk', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '128', name: 'Tristan Stubbs', role: PlayerRole.BATTER, rating: 8.6, points: 8, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '129', name: 'Shikhar Dhawan', role: PlayerRole.BATTER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '130', name: 'Sam Curran', role: PlayerRole.ALL_ROUNDER, rating: 8.7, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast', isDeathBowler: true },
  { id: '131', name: 'Arshdeep Singh', role: PlayerRole.BOWLER, rating: 8.9, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '132', name: 'Jitesh Sharma', role: PlayerRole.WICKETKEEPER, rating: 8.3, points: 7, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '133', name: 'Harshal Patel', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '134', name: 'Shashank Singh', role: PlayerRole.BATTER, rating: 8.2, points: 7, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '135', name: 'Ashutosh Sharma', role: PlayerRole.BATTER, rating: 8.1, points: 7, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '136', name: 'Rahul Chahar', role: PlayerRole.BOWLER, rating: 8.2, points: 7, bowlingType: 'Spin' },
  { id: '137', name: 'Prabhsimran Singh', role: PlayerRole.BATTER, rating: 8.0, points: 7, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '138', name: 'Jonny Bairstow', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '139', name: 'Liam Livingstone', role: PlayerRole.ALL_ROUNDER, rating: 8.6, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '140', name: 'Sikandar Raza', role: PlayerRole.ALL_ROUNDER, rating: 8.4, points: 7, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '141', name: 'Kagiso Rabada', role: PlayerRole.BOWLER, rating: 9.1, points: 9, bowlingType: 'Fast', isDeathBowler: true },
  { id: '142', name: 'Harpreet Brar', role: PlayerRole.BOWLER, rating: 8.1, points: 7, bowlingType: 'Spin' },
  { id: '143', name: 'Kieron Pollard', role: PlayerRole.ALL_ROUNDER, rating: 9.0, points: 9, battingPosition: 'Finisher', bowlingType: 'Fast' },
  { id: '144', name: 'Dwayne Bravo', role: PlayerRole.ALL_ROUNDER, rating: 9.1, points: 9, battingPosition: 'Finisher', bowlingType: 'Fast', isDeathBowler: true },
  { id: '145', name: 'Lasith Malinga', role: PlayerRole.BOWLER, rating: 9.8, points: 10, bowlingType: 'Fast', isDeathBowler: true },
  { id: '146', name: 'Zaheer Khan', role: PlayerRole.BOWLER, rating: 9.4, points: 9, bowlingType: 'Fast' },
  { id: '147', name: 'Anil Kumble', role: PlayerRole.BOWLER, rating: 9.5, points: 10, bowlingType: 'Spin' },
  { id: '148', name: 'Harbhajan Singh', role: PlayerRole.BOWLER, rating: 9.3, points: 9, bowlingType: 'Spin' },
  { id: '149', name: 'Sourav Ganguly', role: PlayerRole.BATTER, rating: 9.2, points: 9, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '150', name: 'VVS Laxman', role: PlayerRole.BATTER, rating: 9.1, points: 9, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '151', name: 'Gautam Gambhir', role: PlayerRole.BATTER, rating: 9.2, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '152', name: 'Virender Sehwag', role: PlayerRole.BATTER, rating: 9.6, points: 10, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '153', name: 'Yuvraj Singh', role: PlayerRole.ALL_ROUNDER, rating: 9.5, points: 10, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '154', name: 'Suresh Raina', role: PlayerRole.BATTER, rating: 9.3, points: 9, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '155', name: 'Robin Uthappa', role: PlayerRole.BATTER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '156', name: 'Ambati Rayudu', role: PlayerRole.BATTER, rating: 8.9, points: 8, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '157', name: 'Shane Watson', role: PlayerRole.ALL_ROUNDER, rating: 9.4, points: 9, battingPosition: 'Top Order', bowlingType: 'Fast' },
  { id: '158', name: 'Brendon McCullum', role: PlayerRole.WICKETKEEPER, rating: 9.3, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '159', name: 'Matthew Hayden', role: PlayerRole.BATTER, rating: 9.4, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '160', name: 'Michael Hussey', role: PlayerRole.BATTER, rating: 9.3, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '161', name: 'Murali Vijay', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '162', name: 'Ravichandran Ashwin', role: PlayerRole.ALL_ROUNDER, rating: 9.1, points: 9, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '163', name: 'Albie Morkel', role: PlayerRole.ALL_ROUNDER, rating: 8.9, points: 8, battingPosition: 'Finisher', bowlingType: 'Fast' },
  { id: '164', name: 'Doug Bollinger', role: PlayerRole.BOWLER, rating: 8.8, points: 8, bowlingType: 'Fast' },
  { id: '165', name: 'Hilfenhaus', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast' },
  { id: '166', name: 'Mohit Sharma', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '167', name: 'Ashish Nehra', role: PlayerRole.BOWLER, rating: 8.9, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '168', name: 'Lungi Ngidi', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast' },
  { id: '169', name: 'Shardul Thakur', role: PlayerRole.ALL_ROUNDER, rating: 8.5, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '170', name: 'Deepak Chahar', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Fast' },
  { id: '171', name: 'Mitchell Starc', role: PlayerRole.BOWLER, rating: 9.2, points: 9, bowlingType: 'Fast', isDeathBowler: true },
  { id: '172', name: 'Pat Cummins', role: PlayerRole.BOWLER, rating: 9.3, points: 9, bowlingType: 'Fast' },
  { id: '173', name: 'Travis Head', role: PlayerRole.BATTER, rating: 9.2, points: 9, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '174', name: 'Abhishek Sharma', role: PlayerRole.ALL_ROUNDER, rating: 8.9, points: 8, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '175', name: 'Heinrich Klaasen', role: PlayerRole.WICKETKEEPER, rating: 9.4, points: 9, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '176', name: 'Nitish Kumar Reddy', role: PlayerRole.ALL_ROUNDER, rating: 8.4, points: 7, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '177', name: 'Abdul Samad', role: PlayerRole.BATTER, rating: 8.1, points: 7, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '178', name: 'Shahbaz Ahmed', role: PlayerRole.ALL_ROUNDER, rating: 8.2, points: 7, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '179', name: 'Bhuvneshwar Kumar', role: PlayerRole.BOWLER, rating: 8.8, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '180', name: 'T Natarajan', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '181', name: 'Mayank Markande', role: PlayerRole.BOWLER, rating: 8.2, points: 7, bowlingType: 'Spin' },
  { id: '182', name: 'Jaydev Unadkat', role: PlayerRole.BOWLER, rating: 8.1, points: 7, bowlingType: 'Fast', isDeathBowler: true },
  { id: '183', name: 'Sanju Samson', role: PlayerRole.WICKETKEEPER, rating: 9.1, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '184', name: 'Yashasvi Jaiswal', role: PlayerRole.BATTER, rating: 9.0, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '185', name: 'Jos Buttler', role: PlayerRole.WICKETKEEPER, rating: 9.3, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '186', name: 'Riyan Parag', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '187', name: 'Shimron Hetmyer', role: PlayerRole.BATTER, rating: 8.5, points: 8, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '188', name: 'Dhruv Jurel', role: PlayerRole.WICKETKEEPER, rating: 8.4, points: 7, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '189', name: 'Ravichandran Ashwin', role: PlayerRole.ALL_ROUNDER, rating: 9.0, points: 9, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '190', name: 'Trent Boult', role: PlayerRole.BOWLER, rating: 9.1, points: 9, bowlingType: 'Fast' },
  { id: '191', name: 'Yuzvendra Chahal', role: PlayerRole.BOWLER, rating: 9.2, points: 9, bowlingType: 'Spin' },
  { id: '192', name: 'Avesh Khan', role: PlayerRole.BOWLER, rating: 8.5, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '193', name: 'Sandeep Sharma', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '194', name: 'Shubman Gill', role: PlayerRole.BATTER, rating: 9.1, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '195', name: 'Sai Sudharsan', role: PlayerRole.BATTER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '196', name: 'David Miller', role: PlayerRole.BATTER, rating: 8.9, points: 8, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '197', name: 'Rahul Tewatia', role: PlayerRole.ALL_ROUNDER, rating: 8.5, points: 8, battingPosition: 'Finisher', bowlingType: 'Spin' },
  { id: '198', name: 'Rashid Khan', role: PlayerRole.ALL_ROUNDER, rating: 9.4, points: 9, battingPosition: 'Finisher', bowlingType: 'Spin' },
  { id: '199', name: 'Mohit Sharma', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '200', name: 'Noor Ahmad', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Spin' },
  { id: '201', name: 'Umesh Yadav', role: PlayerRole.BOWLER, rating: 8.4, points: 7, bowlingType: 'Fast' },
  { id: '202', name: 'Spencer Johnson', role: PlayerRole.BOWLER, rating: 8.3, points: 7, bowlingType: 'Fast' },
  { id: '203', name: 'KL Rahul', role: PlayerRole.WICKETKEEPER, rating: 9.0, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '204', name: 'Quinton de Kock', role: PlayerRole.WICKETKEEPER, rating: 8.9, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '205', name: 'Marcus Stoinis', role: PlayerRole.ALL_ROUNDER, rating: 8.9, points: 8, battingPosition: 'Top Order', bowlingType: 'Fast' },
  { id: '206', name: 'Nicholas Pooran', role: PlayerRole.WICKETKEEPER, rating: 9.1, points: 9, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '207', name: 'Ayush Badoni', role: PlayerRole.BATTER, rating: 8.2, points: 7, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '208', name: 'Krunal Pandya', role: PlayerRole.ALL_ROUNDER, rating: 8.6, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '209', name: 'Ravi Bishnoi', role: PlayerRole.BOWLER, rating: 8.8, points: 8, bowlingType: 'Spin' },
  { id: '210', name: 'Naveen-ul-Haq', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '211', name: 'Mayank Yadav', role: PlayerRole.BOWLER, rating: 8.5, points: 8, bowlingType: 'Fast' },
  { id: '212', name: 'Yash Thakur', role: PlayerRole.BOWLER, rating: 8.2, points: 7, bowlingType: 'Fast', isDeathBowler: true },
  { id: '213', name: 'Rishabh Pant', role: PlayerRole.WICKETKEEPER, rating: 9.2, points: 9, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '214', name: 'David Warner', role: PlayerRole.BATTER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '215', name: 'Prithvi Shaw', role: PlayerRole.BATTER, rating: 8.3, points: 7, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '216', name: 'Jake Fraser-McGurk', role: PlayerRole.BATTER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '217', name: 'Tristan Stubbs', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '218', name: 'Axar Patel', role: PlayerRole.ALL_ROUNDER, rating: 9.0, points: 9, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '219', name: 'Kuldeep Yadav', role: PlayerRole.BOWLER, rating: 9.1, points: 9, bowlingType: 'Spin' },
  { id: '220', name: 'Khaleel Ahmed', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Fast' },
  { id: '221', name: 'Ishant Sharma', role: PlayerRole.BOWLER, rating: 8.3, points: 7, bowlingType: 'Fast' },
  { id: '222', name: 'Mukesh Kumar', role: PlayerRole.BOWLER, rating: 8.4, points: 7, bowlingType: 'Fast', isDeathBowler: true },
  { id: '223', name: 'Shikhar Dhawan', role: PlayerRole.BATTER, rating: 8.9, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '224', name: 'Jonny Bairstow', role: PlayerRole.BATTER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '225', name: 'Prabhsimran Singh', role: PlayerRole.BATTER, rating: 8.2, points: 7, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '226', name: 'Liam Livingstone', role: PlayerRole.ALL_ROUNDER, rating: 8.7, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '227', name: 'Sam Curran', role: PlayerRole.ALL_ROUNDER, rating: 8.8, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast', isDeathBowler: true },
  { id: '228', name: 'Jitesh Sharma', role: PlayerRole.WICKETKEEPER, rating: 8.4, points: 7, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '229', name: 'Shashank Singh', role: PlayerRole.BATTER, rating: 8.4, points: 7, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '230', name: 'Ashutosh Sharma', role: PlayerRole.BATTER, rating: 8.3, points: 7, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '231', name: 'Harpreet Brar', role: PlayerRole.BOWLER, rating: 8.2, points: 7, bowlingType: 'Spin' },
  { id: '232', name: 'Rahul Chahar', role: PlayerRole.BOWLER, rating: 8.3, points: 7, bowlingType: 'Spin' },
  { id: '233', name: 'Arshdeep Singh', role: PlayerRole.BOWLER, rating: 9.0, points: 9, bowlingType: 'Fast', isDeathBowler: true },
  { id: '234', name: 'Harshal Patel', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '235', name: 'Kagiso Rabada', role: PlayerRole.BOWLER, rating: 9.2, points: 9, bowlingType: 'Fast', isDeathBowler: true },
  { id: '236', name: 'Shreyas Iyer', role: PlayerRole.BATTER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '237', name: 'Phil Salt', role: PlayerRole.WICKETKEEPER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '238', name: 'Sunil Narine', role: PlayerRole.ALL_ROUNDER, rating: 9.3, points: 9, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '239', name: 'Venkatesh Iyer', role: PlayerRole.ALL_ROUNDER, rating: 8.6, points: 8, battingPosition: 'Top Order', bowlingType: 'Fast' },
  { id: '240', name: 'Andre Russell', role: PlayerRole.ALL_ROUNDER, rating: 9.2, points: 9, battingPosition: 'Finisher', bowlingType: 'Fast', isDeathBowler: true },
  { id: '241', name: 'Rinku Singh', role: PlayerRole.BATTER, rating: 8.7, points: 8, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '242', name: 'Ramandeep Singh', role: PlayerRole.ALL_ROUNDER, rating: 8.1, points: 7, battingPosition: 'Finisher', bowlingType: 'Fast' },
  { id: '243', name: 'Mitchell Starc', role: PlayerRole.BOWLER, rating: 9.1, points: 9, bowlingType: 'Fast', isDeathBowler: true },
  { id: '244', name: 'Varun Chakaravarthy', role: PlayerRole.BOWLER, rating: 8.9, points: 8, bowlingType: 'Spin' },
  { id: '245', name: 'Harshit Rana', role: PlayerRole.BOWLER, rating: 8.5, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '246', name: 'Vaibhav Arora', role: PlayerRole.BOWLER, rating: 8.2, points: 7, bowlingType: 'Fast' },
  { id: '247', name: 'Suyash Sharma', role: PlayerRole.BOWLER, rating: 8.1, points: 7, bowlingType: 'Spin' },
  { id: '248', name: 'Faf du Plessis', role: PlayerRole.BATTER, rating: 9.0, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '249', name: 'Virat Kohli', role: PlayerRole.BATTER, rating: 9.6, points: 10, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '250', name: 'Will Jacks', role: PlayerRole.ALL_ROUNDER, rating: 8.7, points: 8, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '251', name: 'Rajat Patidar', role: PlayerRole.BATTER, rating: 8.6, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '252', name: 'Glenn Maxwell', role: PlayerRole.ALL_ROUNDER, rating: 8.8, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '253', name: 'Cameron Green', role: PlayerRole.ALL_ROUNDER, rating: 8.9, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '254', name: 'Dinesh Karthik', role: PlayerRole.WICKETKEEPER, rating: 8.5, points: 8, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '255', name: 'Mahipal Lomror', role: PlayerRole.BATTER, rating: 8.1, points: 7, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '256', name: 'Karn Sharma', role: PlayerRole.BOWLER, rating: 8.2, points: 7, bowlingType: 'Spin' },
  { id: '257', name: 'Mohammed Siraj', role: PlayerRole.BOWLER, rating: 8.8, points: 8, bowlingType: 'Fast' },
  { id: '258', name: 'Yash Dayal', role: PlayerRole.BOWLER, rating: 8.3, points: 7, bowlingType: 'Fast' },
  { id: '259', name: 'Lockie Ferguson', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '260', name: 'Swapnil Singh', role: PlayerRole.ALL_ROUNDER, rating: 8.0, points: 7, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '261', name: 'Ishan Kishan', role: PlayerRole.WICKETKEEPER, rating: 8.7, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '262', name: 'Rohit Sharma', role: PlayerRole.BATTER, rating: 9.3, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '263', name: 'Suryakumar Yadav', role: PlayerRole.BATTER, rating: 9.4, points: 9, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '264', name: 'Tilak Varma', role: PlayerRole.BATTER, rating: 8.8, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '265', name: 'Hardik Pandya', role: PlayerRole.ALL_ROUNDER, rating: 8.9, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast', isDeathBowler: true },
  { id: '266', name: 'Tim David', role: PlayerRole.BATTER, rating: 8.5, points: 8, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '267', name: 'Romario Shepherd', role: PlayerRole.ALL_ROUNDER, rating: 8.2, points: 7, battingPosition: 'Finisher', bowlingType: 'Fast' },
  { id: '268', name: 'Mohammad Nabi', role: PlayerRole.ALL_ROUNDER, rating: 8.6, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '269', name: 'Gerald Coetzee', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '270', name: 'Jasprit Bumrah', role: PlayerRole.BOWLER, rating: 9.7, points: 10, bowlingType: 'Fast', isDeathBowler: true },
  { id: '271', name: 'Nuwan Thushara', role: PlayerRole.BOWLER, rating: 8.3, points: 7, bowlingType: 'Fast', isDeathBowler: true },
  { id: '272', name: 'Piyush Chawla', role: PlayerRole.BOWLER, rating: 8.4, points: 7, bowlingType: 'Spin' },
  { id: '273', name: 'Ruturaj Gaikwad', role: PlayerRole.BATTER, rating: 9.1, points: 9, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '274', name: 'Rachin Ravindra', role: PlayerRole.ALL_ROUNDER, rating: 8.8, points: 8, battingPosition: 'Top Order', bowlingType: 'Spin' },
  { id: '275', name: 'Ajinkya Rahane', role: PlayerRole.BATTER, rating: 8.4, points: 7, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '276', name: 'Daryl Mitchell', role: PlayerRole.ALL_ROUNDER, rating: 8.8, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '277', name: 'Shivam Dube', role: PlayerRole.ALL_ROUNDER, rating: 8.9, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '278', name: 'Ravindra Jadeja', role: PlayerRole.ALL_ROUNDER, rating: 9.2, points: 9, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '279', name: 'Sameer Rizvi', role: PlayerRole.BATTER, rating: 8.0, points: 7, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '280', name: 'MS Dhoni', role: PlayerRole.WICKETKEEPER, rating: 9.3, points: 9, battingPosition: 'Finisher', bowlingType: 'None' },
  { id: '281', name: 'Deepak Chahar', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Fast' },
  { id: '282', name: 'Shardul Thakur', role: PlayerRole.ALL_ROUNDER, rating: 8.4, points: 7, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '283', name: 'Tushar Deshpande', role: PlayerRole.BOWLER, rating: 8.3, points: 7, bowlingType: 'Fast' },
  { id: '284', name: 'Mustafizur Rahman', role: PlayerRole.BOWLER, rating: 8.7, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '285', name: 'Matheesha Pathirana', role: PlayerRole.BOWLER, rating: 8.9, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '286', name: 'Maheesh Theekshana', role: PlayerRole.BOWLER, rating: 8.6, points: 8, bowlingType: 'Spin' },
  { id: '287', name: 'Mitchell Santner', role: PlayerRole.ALL_ROUNDER, rating: 8.5, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '288', name: 'Moeen Ali', role: PlayerRole.ALL_ROUNDER, rating: 8.6, points: 8, battingPosition: 'Middle Order', bowlingType: 'Spin' },
  { id: '289', name: 'Devon Conway', role: PlayerRole.WICKETKEEPER, rating: 8.9, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '290', name: 'David Miller', role: PlayerRole.BATTER, rating: 8.8, points: 8, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '291', name: 'Kane Williamson', role: PlayerRole.BATTER, rating: 8.9, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '292', name: 'Matthew Wade', role: PlayerRole.WICKETKEEPER, rating: 8.4, points: 7, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '293', name: 'Wriddhiman Saha', role: PlayerRole.WICKETKEEPER, rating: 8.3, points: 7, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '294', name: 'Azmatullah Omarzai', role: PlayerRole.ALL_ROUNDER, rating: 8.4, points: 7, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '295', name: 'Vijay Shankar', role: PlayerRole.ALL_ROUNDER, rating: 8.1, points: 7, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '296', name: 'Shahrukh Khan', role: PlayerRole.BATTER, rating: 8.2, points: 7, battingPosition: 'Finisher', bowlingType: 'Spin' },
  { id: '297', name: 'Ravisrinivasan Sai Kishore', role: PlayerRole.BOWLER, rating: 8.2, points: 7, bowlingType: 'Spin' },
  { id: '298', name: 'Manav Suthar', role: PlayerRole.BOWLER, rating: 8.0, points: 7, bowlingType: 'Spin' },
  { id: '299', name: 'Darshan Nalkande', role: PlayerRole.BOWLER, rating: 7.9, points: 6, bowlingType: 'Fast' },
  { id: '300', name: 'Kartik Tyagi', role: PlayerRole.BOWLER, rating: 8.1, points: 7, bowlingType: 'Fast' },
  { id: '301', name: 'Sushant Mishra', role: PlayerRole.BOWLER, rating: 7.8, points: 6, bowlingType: 'Fast' },
  { id: '302', name: 'Sandip Warrier', role: PlayerRole.BOWLER, rating: 8.0, points: 7, bowlingType: 'Fast' },
  { id: '303', name: 'BR Sharath', role: PlayerRole.WICKETKEEPER, rating: 7.7, points: 6, battingPosition: 'Middle Order', bowlingType: 'None' },
  { id: '304', name: 'Gurnoor Brar', role: PlayerRole.BOWLER, rating: 7.6, points: 6, bowlingType: 'Fast' },
  { id: '305', name: 'Tanay Thyagarajan', role: PlayerRole.BOWLER, rating: 7.5, points: 6, bowlingType: 'Spin' },
  { id: '306', name: 'Jhye Richardson', role: PlayerRole.BOWLER, rating: 8.4, points: 7, bowlingType: 'Fast' },
  { id: '307', name: 'Nathan Ellis', role: PlayerRole.BOWLER, rating: 8.5, points: 8, bowlingType: 'Fast', isDeathBowler: true },
  { id: '308', name: 'Chris Woakes', role: PlayerRole.ALL_ROUNDER, rating: 8.6, points: 8, battingPosition: 'Middle Order', bowlingType: 'Fast' },
  { id: '309', name: 'Rilee Rossouw', role: PlayerRole.BATTER, rating: 8.5, points: 8, battingPosition: 'Top Order', bowlingType: 'None' },
  { id: '310', name: 'Tom Curran', role: PlayerRole.ALL_ROUNDER, rating: 8.3, points: 7, battingPosition: 'Finisher', bowlingType: 'Fast', isDeathBowler: true },
];
